# Generated by Django 3.2.7 on 2021-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0060_alter_answeroption_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='guid',
            field=models.UUIDField(null=True),
        ),
    ]
